# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # https://github.com/mosn/layotto/blob/main/docker/layotto-etcd/docker-compose.yml
      etcd:
        image: bitnami/etcd
        env:
          ALLOW_NONE_AUTHENTICATION: yes
          ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
          ETCD_LISTEN_CLIENT_URLS: http://etcd:2379
        ports:
          - 2379:2379
          - 2380:2380

    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:
    - name: Checkout Git Source
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Bootstrap layotto
      run: |
        cd demo
        wget -q https://github.com/mosn/layotto/releases/download/v0.4.0/layotto.linux_amd64.zip
        unzip layotto.linux_amd64.zip
        chmod +x layotto
        ./layotto start -c ./config_with_config_store.json &

    - name: Install Dependencies
      run: npm i

    - name: Continuous Integration
      run: npm run ci

    - name: Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
